env: development
dsn: widgets:secret@tcp(127.0.0.1:3306)/widgets?parseTime=true&tls=false
secretKey: JustABe2BeBlockOfBe2BeVeryRandom

web:
  hostInterface: localhost
  port: 4000
  dsn: widgets:secret@tcp(127.0.0.1:3306)/widgets?parseTime=true&tls=false

api:
  hostInterface: localhost
  port: 4001
  dsn: widgets:secret@tcp(127.0.0.1:3306)/widgets?parseTime=true&tls=false

urls:
  frontend: http://localhost:4000
  api: http://localhost:4001
  invoice: http://localhost:5000/invoice/create-and-send

smtp:
  host: sandbox.smtp.mailtrap.io
  port: 587
  username: 25853d08526311
  password: 399982fbb4cbe9

payment:
  stripe:
    key: pk_test_51PbNQJAmpQVYH1go2dhZHbpjNtORcVyaGAAEiuKI0Gy8Uk3vuXRLCOy5YGqYTLohNEmkph9fMiQwZVvHsRLiz09m00TrybUDVX
    secret: sk_test_51PbNQJAmpQVYH1goK1AAe0OzKXyXwOMneDmKEG9gC2TvIJh5kRolff1ph5QkCyUsGX3foNk1BEPUzffSSxQUUTME00PibhFZo0
